# Generated by Django 5.0.1 on 2026-02-23 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeParseJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.IntegerField(blank=True, help_text='Processing duration in seconds', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_parse_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedResumeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_json', models.JSONField(help_text='Raw JSON returned by the LLM')),
                ('validated_data', models.JSONField(help_text='Pydantic-validated resume data')),
                ('confidence_score', models.FloatField(db_index=True)),
                ('extraction_method', models.CharField(choices=[('pdfplumber', 'PDFPlumber'), ('ocr', 'OCR')], max_length=20)),
                ('llm_model', models.CharField(max_length=80)),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('llm_cost', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='parser.resumeparsejob')),
            ],
            options={
                'db_table': 'parsed_resume_data',
            },
        ),
        migrations.AddIndex(
            model_name='resumeparsejob',
            index=models.Index(fields=['status', 'created_at'], name='resume_pars_status_25fdcb_idx'),
        ),
    ]
